In [1]:
import pandas as pd

In [3]:
pd.read_csv('cleaned_data.csv')

,Unnamed: 0,State,Gender,Maths %,Reading %,Science %,Social %,Total
0,170622,AN,1,0.000000,0.000,27.270,62.00,22.317500
1,171771,AN,1,1.670000,3.335,44.640,30.00,19.911250
2,170610,AN,1,3.330000,6.670,47.270,40.00,24.317500
3,169987,AN,1,3.390000,36.670,30.910,18.00,22.242500
4,170612,AN,1,5.000000,10.000,52.730,26.00,23.432500
5,170611,AN,1,5.080000,3.330,17.860,60.00,21.567500
6,170613,AN,1,5.080000,13.330,57.140,22.00,24.387500
7,169847,AN,1,6.670000,13.330,33.930,34.00,21.982500
8,169652,AN,1,6.780000,6.670,10.710,10.00,8.540000
9,169805,AN,1,8.330000,16.670,23.210,24.00,18.052500
10,171626,AN,1,8.330000,20.000,17.860,10.00,14.047500
11,170208,AN,1,8.470000,6.670,7.140,28.00,12.570000
12,171117,AN,1,8.470000,26.670,19.640,16.00,17.695000
13,170596,AN,1,10.000000,30.000,27.095,24.00,22.773750
14,170212,AN,1,10.170000,23.330,34.550,32.00,25.012500
15,170441,AN,1,10.170000,63.330,29.090,36.00,34.647500
16,170937,AN,1,11.670000,23.330,26.790,18.00,19.947500
17,170683,AN,1,11.670000,26.670,30.360,22.00,22.675000
18,171466,AN,1,11.860000,6.670,18.180,26.00,15.677500
19,171818,AN,1,11.860000,10.000,7.270,4.00,8.282500
20,169709,AN,1,11.860000,20.000,49.090,28.00,27.237500
21,171048,AN,1,11.860000,23.330,30.360,22.00,21.887500
22,171120,AN,1,11.860000,50.000,23.210,42.00,31.767500
23,170911,AN,1,12.348571,63.330,25.000,14.00,28.669643
24,171777,AN,1,13.330000,0.000,33.930,36.00,20.815000
25,170112,AN,1,13.330000,16.670,21.820,42.00,23.455000
26,170804,AN,1,13.330000,23.330,14.290,6.00,14.237500
27,170980,AN,1,13.330000,23.330,23.640,18.00,19.575000
28,170144,AN,1,13.330000,26.670,19.640,20.00,19.910000
29,170190,AN,1,13.330000,26.670,32.730,34.00,26.682500
...,...,...,...,...,...,...,...,...
167330,164216,WB,2,96.610000,93.330,75.000,54.00,79.735000
167331,167288,WB,2,96.610000,93.330,75.000,58.00,80.735000
167332,168691,WB,2,96.610000,93.330,75.000,60.00,81.235000
167333,168969,WB,2,96.610000,93.330,75.000,66.00,82.735000
167334,164870,WB,2,96.610000,93.330,75.000,76.00,85.235000
167335,167183,WB,2,96.610000,93.330,75.000,78.00,85.735000
167336,168989,WB,2,96.610000,93.330,75.000,80.00,86.235000
167337,168752,WB,2,96.610000,93.330,75.000,82.00,86.735000
167338,168993,WB,2,96.610000,93.330,75.000,86.00,87.735000
167339,164923,WB,2,96.610000,93.330,76.360,64.58,82.720000
167340,162961,WB,2,96.610000,93.330,76.360,66.00,83.075000
167341,165715,WB,2,96.610000,93.330,78.180,64.58,83.175000
167342,166776,WB,2,96.610000,93.330,78.180,66.67,83.697500
167343,168773,WB,2,96.610000,93.330,78.180,68.75,84.217500
167344,168998,WB,2,96.610000,93.330,78.180,85.42,88.385000
167345,165713,WB,2,96.610000,93.330,80.000,64.58,83.630000
167346,164867,WB,2,96.610000,93.330,81.820,58.33,82.522500
167347,168924,WB,2,96.610000,93.330,81.820,58.33,82.522500
167348,167184,WB,2,96.610000,93.330,81.820,62.50,83.565000
167349,167170,WB,2,96.610000,93.330,81.820,70.83,85.647500
167350,165379,WB,2,96.610000,93.330,81.820,75.00,86.690000
167351,164874,WB,2,96.610000,93.330,85.450,72.92,87.077500
167352,168972,WB,2,96.610000,93.330,85.450,77.08,88.117500
167353,165366,WB,2,96.610000,93.330,85.710,82.00,89.412500
167354,164878,WB,2,96.610000,93.330,87.270,66.67,85.970000
167355,165396,WB,2,96.610000,93.330,89.290,48.00,81.807500
167356,165393,WB,2,96.610000,93.330,90.910,45.83,81.670000
167357,166832,WB,2,96.610000,93.330,90.910,72.92,88.442500
167358,165383,WB,2,96.610000,93.330,90.910,75.00,88.962500
167359,164871,WB,2,96.610000,93.330,90.910,77.08,89.482500